const mongoose = require('mongoose')
const report = new mongoose.Schema({
    term:{
        type:String,
        required:true,
        unique:true
    },
    report:{
        type:String,
        default:'No Report Needed'
    }
})
const StudentSchem = new mongoose.Schema({
    RegNo:{
        type:String,
        required:true,
        unique:true
    },
    Class:{
        type:String,
        required:true
    },
    Year:{
        type:Number,
        enum:[1,2,3],
        required:true
    },
    PersonalQs:{type:[String]},
    SocialQs:{type:[String]},
    AcademicQs:{type:[String]},
    OccupationalQs:{type:[String]},
    RecreationalQs:{type:[String]},
    PersonalAns:{
        type:[String],
        required:true,
        enum:["Yes","No","C_p1","C_p2","NA","NE"],
    },
    SocailAns:{
        type:[String],
        required:true,
        enum:["Yes","No","C_p1","C_p2","NA","NE"],
    },
    AcademicAns:{
        type:[String],
        required:true,
        enum:["Yes","No","C_p1","C_p2","NA","NE"],
    },
    OccupationalAns:{
        type:[String],
        required:true,
        enum:["Yes","No","C_p1","C_p2","NA","NE"],
    },
    RecreationalAns:{
        type:[String],
        required:true,
        enum:["A","B","C","D","E"],
    },
    Report:report
})
module.export = mongoose.model('student',StudentSchem)